modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Iunius118/Type18GrenadeLauncher/issues"

[[mods]]
modId="type18grenadelauncher"
version="${version}"
displayName="Type 18 Grenade Launcher"
# updateJSONURL=""
displayURL="https://github.com/Iunius118/Type18GrenadeLauncher"
# logoFile=""
credits="Iunius118"
authors="Iunius118"
description="Adds grenade launchers and their ammunition."

[[dependencies.tolaserblade]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tolaserblade]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
